# Generated by Django 5.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='運動名稱', max_length=100)),
                ('description', models.TextField(blank=True, help_text='運動描述')),
                ('difficulty_level', models.IntegerField(choices=[(1, '初級'), (2, '中級'), (3, '高級')], default=1, help_text='難度等級')),
                ('target_muscles', models.JSONField(default=list, help_text='目標肌群列表')),
                ('instructions', models.JSONField(default=list, help_text='動作要領說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoseKeypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='關鍵點名稱', max_length=50, unique=True)),
                ('index', models.IntegerField(help_text='OpenPose 關鍵點索引', unique=True)),
                ('description', models.TextField(blank=True, help_text='關鍵點描述')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名稱', max_length=200)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('standard_keypoints', models.JSONField(help_text='標準姿勢關鍵點')),
                ('scoring_criteria', models.JSONField(default=dict, help_text='評分標準和權重')),
                ('error_detection_rules', models.JSONField(default=list, help_text='錯誤檢測規則')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='exercise.exercisetype')),
            ],
            options={
                'ordering': ['exercise_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_name', models.CharField(help_text='訓練名稱', max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('total_reps', models.IntegerField(default=0, help_text='總次數')),
                ('average_score', models.FloatField(blank=True, help_text='平均分數', null=True)),
                ('notes', models.TextField(blank=True, help_text='訓練備註')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exercise.exercisetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PoseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame_number', models.IntegerField(help_text='幀數')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('keypoints', models.JSONField(help_text='關鍵點座標和信心度')),
                ('pose_score', models.FloatField(help_text='姿勢分數 (0-100)')),
                ('confidence_score', models.FloatField(help_text='信心度分數 (0-1)')),
                ('detected_errors', models.JSONField(default=list, help_text='檢測到的姿勢錯誤')),
                ('ai_feedback', models.TextField(blank=True, help_text='AI 生成的建議')),
                ('image', models.ImageField(blank=True, help_text='分析時的影像截圖', null=True, upload_to='pose_analysis/%Y/%m/%d/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_analyses', to='exercise.exercisesession')),
            ],
            options={
                'ordering': ['session', 'frame_number'],
            },
        ),
    ]
