# Generated by Django 5.2 on 2025-04-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Fallback identifier for anonymous users', max_length=40)),
                ('image', models.ImageField(help_text='Uploaded food image', upload_to='history/%Y/%m/%d/')),
                ('detections', models.JSONField(help_text='List of detected items and their calories')),
                ('total_calories', models.IntegerField(help_text='Sum of calories for this entry')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this scan was performed')),
                ('user', models.ForeignKey(blank=True, help_text='The logged‐in user (blank if anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
