# Generated by Django 5.2.1 on 2025-06-06 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weight', models.FloatField(help_text='Starting weight in kg')),
                ('target_weight', models.FloatField(help_text='Target weight in kg')),
                ('current_weight', models.FloatField(help_text='Current weight in kg')),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentary (little/no exercise)'), (1.375, 'Light activity (light exercise 1-3 days/week)'), (1.55, 'Moderate activity (moderate exercise 3-5 days/week)'), (1.725, 'Very active (hard exercise 6-7 days/week)'), (1.9, 'Extra active (very hard exercise, physical job)')])),
                ('goal', models.CharField(choices=[('maintain', 'Maintain Weight'), ('lose', 'Lose Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=10)),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, help_text='BMR calculated at this weight', null=True)),
                ('tdee', models.FloatField(blank=True, help_text='TDEE calculated at this weight', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
