# Generated by Django 5.2 on 2025-06-28 16:43

import apps.nutrition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightrecord",
            name="date",
            field=models.DateField(default=apps.nutrition.models.get_today_date),
        ),
    ]
